name: hgit
version: 0.1.0.0
synopsis: merkle all the things
github: inanna-malick/merklenoke 
author: Inanna Malick
category: Development

ghc-options: -Wall

default-extensions:
  - DerivingStrategies
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - KindSignatures
  - NoStarIsType
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - TupleSections
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeOperators

dependencies:
  - base >=4.8
  - aeson
  - aeson-gadt-th
  - clay
  - containers
  - bytestring
  - directory
  - deriving-compat
  - http-client
  - hedgehog
  - merkle-schemes
  - merkle-schemes-ext
  - merkle-schemes-higher
  - mtl
  - optparse-applicative
  - recursion-schemes
  - safe-exceptions
  - servant
  - servant-client
  - servant-server
  - singletons
  - split
  - stm
  - text
  - transformers
  - warp
  - threepenny-gui
  - threepenny-gui-flexbox

library:
  source-dirs: src
  exposed-modules:
    - HGit.Core.MergeTrie
    - HGit.Core.Types
    - HGit.GUI.CSS
    - HGit.GUI.Elements
    - HGit.GUI.Messages
    - HGit.GUI.State
    - HGit.GUI.Core

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - hgit

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - hgit
      - temporary
    build-tools: hspec-discover
